spring:
  application:
    name: gateway
  cloud:
    config:
      # This allows the app to start even if config-server is slow
      fail-fast: false 
      retry:
        initial-interval: 2000
        max-attempts: 10
  # Points to the config server
  config:
    import: "optional:configserver:http://user:${CONFIG_SERVICE_PASSWORD}@config-service:8888"

server:
  port: 4000