spring:
  application:
    name: gateway
  configuration-processor:
    enabled: true
  config:
    import: "optional:configserver:http://config:8888"
  cloud:
    config:
      fail-fast: true
      username: user
      password: ${CONFIG_SERVICE_PASSWORD}
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/uaa/**
          filters:
            - StripPrefix=1
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**
          filters:
            - StripPrefix=1
        - id: statistics-service
          uri: lb://STATISTICS-SERVICE
          predicates:
            - Path=/statistics/**
          filters:
            - StripPrefix=1