spring:
  data:
    mongodb:
      uri: mongodb://user:${MONGODB_PASSWORD}@account-mongodb:27017/finedge?authSource=admin

  security:
    oauth2:
      client:
        registration:
          piggymetrics:
            client-id: account-service
            client-secret: ${ACCOUNT_SERVICE_PASSWORD}
            authorization-grant-type: client_credentials
            scope: server
        provider:
          piggymetrics:

            token-uri: http://auth-service:8080/oauth/token