spring:
  data:
    mongodb:
      # Host must match the container name in docker-compose
      host: account-mongodb 
      port: 27017
      database: piggymetrics
      # If you set credentials in your mongo container, uncomment these:
      # username: user
      # password: ${MONGODB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          piggymetrics:
            client-id: account-service
            client-secret: ${ACCOUNT_SERVICE_PASSWORD}
            authorization-grant-type: client_credentials
            scope: server
        provider:
          piggymetrics:
            token-uri: http://auth-service:5000/uaa/oauth/token