logging:
  level:
    org.springframework.security: INFO


# Modern OAuth2 Resource Server setting - CLEANED
spring:
  rabbitmq:
    host: rabbitmq
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8080/.well-known/jwks.json