logging:
  level:
    org.springframework.security: INFO

# Kubernetes replaces Eureka
spring:
  rabbitmq:
    host: rabbitmq

# Modern OAuth2 Resource Server setting
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://auth-service:5000/uaa/.well-known/jwks.json