spring:
  datasource:
    # Use the name 'auth-postgres' to match your docker-test.yml service name
    url: jdbc:postgresql://auth-postgres:5432/finedge
    username: user
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

server:
  # REMOVE context-path to go truly UAA-free
  port: 8080 # Use 8080 to match standard Docker internal networking