spring:
  datasource:
    # Pointing to the Postgres container (auth-db)
    url: jdbc:postgresql://auth-db:5432/finedge
    username: user
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 'update' will automatically create the 'users' table based on your User.java
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /uaa
  port: 5000