spring:
  data:
    mongodb:
      host: auth-db
      port: 27017
      # Changed database name to finedge
      database: finedge
      username: user
      password: ${MONGODB_PASSWORD}
      authentication-database: admin

server:
  servlet:
    context-path: /uaa
  port: 5000