spring:
  cloud:
    gateway:
      routes:
        - id: ui-welcome-page
          uri: forward:/index.html
          predicates:
            - Path=/
        
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/uaa/**
          filters:
            - StripPrefix=1
            
        - id: account-service
          uri: http://account-service:8080
          predicates:
            - Path=/accounts/**
          filters:
            - StripPrefix=1

        # --- NEW SERVICES ---
        - id: statistics-service
          uri: http://statistics-service:8080
          predicates:
            - Path=/statistics/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: http://notification-service:8080
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1

server:
  port: 4000